version: '3'

services:
    app:
        build: .
        container_name: jupyter
        command: jupyter lab --ip=0.0.0.0 --port=8080
        volumes: 
            - .:/home/jupyter/app
        ports:
            - "8080:8080"